// Approved cryptocurrencies list - exactly 142 currencies (includes CRO, QTUM)
export const APPROVED_CURRENCIES: Record<string, string> = {
  '1INCH': '1inch Network',
  'AAVE': 'Aave',
  'ALGO': 'Algorand',
  'APT': 'Aptos',
  'ARB': 'Arbitrum',
  'ARV': 'Ariva',
  'ARK': 'Ark',
  'AVAXC': 'Avalanche',
  'AVAX': 'AVAX',
  'AXS': 'Axie Infinity',
  'BAT': 'Basic Attention Token',
  'BAZED': 'Bazed Games',
  'BEAM': 'Beam',
  'BERA': 'Berachain',
  'BNBBSC': 'Binance Coin (BSC)',
  'BUSDBSC': 'Binance USD',
  'BTC': 'Bitcoin',
  'BCH': 'Bitcoin Cash',
  'BRETTBASE': 'Brett',
  'CAKE': 'CAKE',
  'ADA': 'Cardano',
  'CSPR': 'Casper',
  'LINK': 'Chainlink',
  'CSWAP': 'ChainSwap',
  'CHZ': 'Chiliz',
  'CFX': 'Conflux',
  'CFXMAINNET': 'Conflux',
  'ATOM': 'Cosmos',
  'COTI': 'COTI',
  'CRO': 'Crypto.com Coin',
  'CROMAINNET': 'Cronos',
  'DAI': 'DAI',
  'DASH': 'Dash',
  'MANA': 'Decentraland',
  'DOGE': 'Dogecoin',
  'ENJ': 'Enjin Coin',
  'ETH': 'Ethereum',
  'ETHARB': 'Ethereum',
  'ETHBASE': 'Ethereum',
  'ZKSYNC': 'Ethereum (zkSync Era)',
  'ETC': 'Ethereum Classic',
  'FTM': 'Fantom',
  'FTMMAINNET': 'Fantom',
  'FIL': 'Filecoin',
  'FLOKI': 'Floki',
  'FRONT': 'Frontier',
  'FTT': 'FTT',
  'FUN': 'FUNToken',
  'GALAERC20': 'GALAERC20',
  'ONE': 'Harmony',
  'HBAR': 'Hedera Hashgraph',
  'HEX': 'Hex',
  'HYPE': 'Hyperliquid',
  'ILV': 'Illuvium',
  'INJERC20': 'Injective',
  'INJMAINNET': 'Injective Protocol',
  'INJ': 'Injective Protocol',
  'IOTA': 'IOTA',
  'IOTX': 'IOTX',
  'JASMY': 'JasmyCoin',
  'JETTON': 'JetTon Games',
  'KAIA': 'Kaia',
  'KAS': 'Kaspa',
  'KMD': 'Komodo',
  'KNC': 'Kyber Network Crystal',
  'ZROARB': 'LayerZero (Arbitrum)',
  'LGCY': 'LGCY Network',
  'LTC': 'Litecoin',
  'MATIC': 'Polygon',
  'XMR': 'Monero',
  'MYRO': 'Myro',
  'NANO': 'Nano',
  'NEAR': 'Near',
  'NEO': 'NEO',
  'NOT': 'Notcoin',
  'OCEAN': 'Ocean Protocol',
  'TRUMP': 'OFFICIAL TRUMP',
  'OKB': 'OKB',
  'OMG': 'OMG Network',
  'PYUSD': 'PayPal USD',
  'PEPE': 'Pepe',
  'DOT': 'Polkadot',
  'MATICMAINNET': 'Polygon',
  'PLS': 'Pulsechain',
  'QTUM': 'QTUM',
  'RVN': 'Ravencoin',
  'XRP': 'Ripple',
  'SEI': 'Sei',
  'SHIB': 'Shiba Inu',
  'SOL': 'Solana',
  'STX': 'Stacks',
  'STRKMAINNET': 'Starknet',
  'XLM': 'Stellar',
  'STRAX': 'Stratis',
  'SUI': 'Sui',
  'SUPER': 'SUPER',
  'TET': 'Tectum',
  'TENSHI': 'Tenshi',
  'LUNA': 'Terra',
  'LUNC': 'Terra Classic',
  'USDTARB': 'Tether',
  'USDTARC20': 'Tether',
  'USDTOP': 'Tether',
  'USDTBSC': 'Tether USD',
  'USDTCELO': 'Tether USD',
  'USDTERC20': 'Tether USD',
  'USDTMATIC': 'Tether USD',
  'USDTSOL': 'Tether USD',
  'USDTTON': 'Tether USD',
  'USDTTRC20': 'Tether USD',
  'XTZ': 'Tezos',
  'GRT': 'The Graph',
  'THETA': 'THETA',
  'RUNE': 'THORChain',
  'TON': 'Toncoin',
  'TRX': 'Tron',
  'TUSDTRC20': 'TrueUSD',
  'UNI': 'Uniswap',
  'USDCALGO': 'USD Coin',
  'USDCARC20': 'USD Coin',
  'USDCBASE': 'USD Coin',
  'USDCBSC': 'USD Coin',
  'USDC': 'USD Coin',
  'USDCOP': 'USD Coin',
  'USDCMATIC': 'USD Coin',
  'USDCSOL': 'USD Coin',
  'USDCARB': 'USD Coin',
  'OPUSDCE': 'USD Coin',
  'MATICUSDCE': 'USD Coin',
  'VET': 'VeChain',
  'VLX': 'Velas',
  'VELO': 'Velo',
  'VERSE': 'Verse',
  'WAVES': 'Waves',
  'WBTCMATIC': 'Wrapped Bitcoin (Polygon)',
  'XDC': 'XDC Network',
  'XYO': 'XYO Network',
  'YFI': 'yearn.finance',
  'ZBC': 'Zebec Protocol',
  'ZEC': 'Zcash',
  'ZK': 'zkSync',
  'ZROERC20': 'LayerZero (Ethereum)'
};

// Helper to check if currency is approved
export function isApprovedCurrency(code: string): boolean {
  return code.toUpperCase() in APPROVED_CURRENCIES;
}

// Helper to get display name for approved currency
export function getApprovedDisplayName(code: string): string {
  return APPROVED_CURRENCIES[code.toUpperCase()] || code;
}