name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: yarn install
    - name: Generate Supabase Types
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: yarn generate-types
    - name: Normalize Supabase Type Metadata and Format
      run: |
        # Apply the normalization
        perl -0pi -e 's/__InternalSupabase:\s*\{.*?\n\s*\}/__InternalSupabase: {\n    PostgrestVersion: "normalized"\n  }/s' types/database.types.ts
        # Ensure consistent formatting by removing extra blank lines and normalizing spacing
        sed -i '/^[[:space:]]*$/N;/^[[:space:]]*\n[[:space:]]*$/d' types/database.types.ts
        # Ensure there's exactly one blank line after the __InternalSupabase block
        sed -i '/PostgrestVersion: "normalized"/,/^[[:space:]]*$/{/^[[:space:]]*$/d;}' types/database.types.ts
        sed -i '/PostgrestVersion: "normalized"/a\\n' types/database.types.ts
    - name: Check for Type Changes
      run: git diff --exit-code types/database.types.ts || (echo "Types changed - run gen types locally" && exit 1)
    - run: yarn lint
    - run: yarn type-check
